[tool.black]
line-length = 99
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.mypy]
warn_unused_ignores = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
show_error_codes = true
implicit_optional = true

[tool.ruff]
fix = false
output-format = "grouped"
line-length = 99
